language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 5.5
          env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; else INI_FILE=/etc/hhvm/php.ini; fi;
    - echo "memory_limit = -1" >> $INI_FILE
    - echo "session.gc_probability = 0" >> $INI_FILE
    - composer self-update
    - composer --version
    - wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar

install:
    - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-source $COMPOSER_FLAGS

script:
    - php php-cs-fixer.phar fix --dry-run -v
    - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php bin/coveralls -v
